server:
#  port: 8081
spring:
  application:
    name: shopex
    thymeleaf:
      cache: false
      mode: html
  profiles:
    active: test

mybatis:
    type-aliases-package: com.hellojd.shopex.domain
    mapper-locations: classpath:mapper/*.xml