server:
  port: 8060
spring:
  application:
    name: shopex
    thymeleaf:
      cache: false
      mode: html

mybatis:
    type-aliases-package: com.hellojd.shopex.domain
    mapper-locations: classpath:mapper/*.xml