server:
  port: 9090
spring:
  application:
    name: shopex
    thymeleaf:
      cache: false
      mode: html
  datasource:
    url:  jdbc:h2:~/shopex_db;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
mybatis:
    type-aliases-package: com.hellojd.shopex.domain
    mapper-locations: classpath:mapper/*.xml