server:
  port: 9090
spring:
  application:
    name: shopex
    thymeleaf:
      cache: false
      mode: html
    h2:
      console:
        settings.web-allow-others: true #远程访问
        enabled: true # 默认启动程序启动
        path: /h2 #访问路径 localhost:9100/h2
  datasource:
    url:  jdbc:h2:~/shopex_db;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
mybatis:
    type-aliases-package: com.hellojd.shopex.domain
    mapper-locations: classpath:mapper/*.xml